### PR TITLE
Update: readme

### PR DESCRIPTION
**Pull request by 00thirdeye00**
Readme file updated for setting up build environment for the project

### CODE REVIEW

**Review by robotman2412 — CHANGES_REQUESTED** [review]
Could you use single-line code blocks instead of having multiple lines every time?
Example:
```
For Ubuntu, run: `<some command>`
To <do xyz>, run: `<some command>`
```

**Comment by robotman2412** [comment]
I do not know why the CI checks failed, they shouldn't as this only edits the README. We'll ignore that they failed.

**Comment by 00thirdeye00** [comment]
> Could you use single-line code blocks instead of having multiple lines every time? Example:
> 
> ```
> For Ubuntu, run: `<some command>`
> To <do xyz>, run: `<some command>`
> ```

I modified from `single line code` (earlier version) to `code block` type for better understanding. Also, one can copy the code when we have longer commands and execute it. I also have feeling that this is not enough readme for someone to give a head start so I will update it again in the near future.

**Comment by robotman2412** [comment]
No, this clutters the README. It's fine if you want to add commands but, unless they are very long, please put them on a single line.

**Review by robotman2412 — CHANGES_REQUESTED** [review]
There is a small inconsistency in the ubuntu install lines and I think it would be best to make it one command before the list of prerequisites, clearly stating that this installs all prerequisites.

**Comment by 00thirdeye00** [comment]
> There is a small inconsistency in the ubuntu install lines and I think it would be best to make it one command before the list of prerequisites, clearly stating that this installs all prerequisites.

unlear?

**Comment by robotman2412** [comment]
They're two apt-get install commands and if you're going to bother adding those commands, just make it one. And if you make it just one, put it before the lists of packages and state something like "On Ubuntu, run this: ....
Or install: ...."

**Pull request merged**
